Web/Pages/Template/Components/CommonComponent/SeoGenerator/SeoGeneratorViewComponent.cs
using Common.Utilities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ResourceLibrary.Resources.SEO;
using Services.Services.CMS.Setting;
using SharedModels.Dtos;
using System.ComponentModel.DataAnnotations;
 

namespace Web.Pages.Template.Components.CommonComponent.SeoGenerator
{
    public class SeoGeneratorViewComponent:ViewComponent
    {
      

        public IViewComponentResult Invoke(SettingSelectDto setting)
        {
            SEODto PageSeo = new SEODto();
          

            VCSEOModel model = new VCSEOModel()
            {
                FavIcon=setting.FavIconUrl,
                Path=PageSeo.Path,
                SEODesc=TextUtility.TextLimit(PageSeo.SEODesc,170 ,true),
                SEOPic=PageSeo.SEOPic,
                SEOTitle=PageSeo.SEOTitle,
                SiteName = setting.SiteTitle,
                Date=PageSeo.Date
            };   

            return View("/Pages/Template/Components/CommonComponent/SeoGenerator/Index.cshtml", model);
        }
    }

    public class VCSEOModel
    {
        public string? Path { get; set; }
        public string? SEOTitle { get; set; }
        public string? SEODesc { get; set; }
        public string? SEOPic { get; set; }
        public string? FavIcon { get; set; }
        public string? SiteName { get; set; }

        public DateTime? Date { get; set; }
    }
}

Web/Pages/Shared/_AuthLayout.cshtml
@using Common;
@using Microsoft.Extensions.Options;
@using System.Globalization;
@inject IOptionsSnapshot<ProjectSettings> settings;
@inject IStringLocalizer<ResourceLibrary.Panel.Common.Auth.Layout.Layout> Localizer;
@{
     bool isRTL = CultureInfo.CurrentUICulture.TextInfo.IsRightToLeft;
   
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link async href="~/DTCMS/bundle/css/bundle.css" rel="stylesheet" asp-append-version="true">
    <link rel="manifest" href="/DTCMS/manifest/manifest.json">
    <meta name="theme-color" content="#3986D1">

</head>
<body dir='@(isRTL == true? "rtl":"ltr")'>



    <main
          class="bg-gray-50 min-h-screen pt-6">
        <div class="  max-w-2xl mx-auto">
            <div class="flex justify-between px-4 mb-16">
                <a href="/">
                  <svg width="67" height="67" viewBox="0 0 67 67" fill="none" xmlns="http://www.w3.org/2000/svg">
<rect width="66.9875" height="66.9875" fill="black"/>
<rect x="4.26367" y="4.26367" width="58.4221" height="58.4221" fill="white"/>
<circle cx="43.2563" cy="17.6993" r="5.79395" fill="#F19100"/>
<path d="M20.4917 51.8733V17.0086H34.2469C36.8799 17.0086 39.127 17.4796 40.9883 18.4216C42.8609 19.3522 44.2852 20.6744 45.2613 22.3881C46.2486 24.0905 46.7423 26.0936 46.7423 28.3975C46.7423 30.7127 46.243 32.7045 45.2442 34.3728C44.2455 36.0298 42.7985 37.3009 40.9032 38.1862C39.0192 39.0714 36.738 39.514 34.0596 39.514H24.8497V33.5898H32.8679C34.2752 33.5898 35.4442 33.3968 36.3748 33.0109C37.3055 32.6251 37.9978 32.0463 38.4517 31.2745C38.9171 30.5028 39.1497 29.5438 39.1497 28.3975C39.1497 27.2399 38.9171 26.2639 38.4517 25.4694C37.9978 24.675 37.2998 24.0735 36.3578 23.6649C35.4272 23.245 34.2525 23.035 32.8339 23.035H27.863V51.8733H20.4917ZM39.32 36.0071L47.9851 51.8733H39.8477L31.3699 36.0071H39.32Z" fill="black"/>
</svg>


                </a>

                <img src="~/DTCMS/assets/images/icon/backArrow.svg"
                     alt="Back"
                     class="ltr:rotate-180 cursor-pointer self-center"
                     onclick="window.history.back()"
                     
                />
            </div>
            
            @RenderBody()

            <div class="flex justify-center items-center mt-[60px] mx-4  md:mx-0">
                <div>
                    @Localizer["Poweredby"]
                    <a class="mx-1"
                    target="_blank"
                    href="https://dariatech.com"><b class="font-bold">DariaCMS</b></a>
                </div>

                
            </div>
        </div>
            <div id="toastContainerArea" class=" fixed bottom-6 right-2/4 translate-x-1/2 hidden items-center w-full max-w-[344px]  p-4" role="alert">
            <div   id="toastMessageArea"></div>
            <button type="button"
            onclick="closeToast()"
                class=" absolute rtl:left-4 ltr:right-4 top-[25px] bg-transparent text-gray-400 rounded-lg focus:ring-2 p-1.5 inline-flex py-4 w-8"
                aria-label="Close">
                <span class="sr-only">Close</span>
                <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd"
                        d="M0.292893 0.292893C0.683417 -0.0976311 1.31658 -0.0976311 1.70711 0.292893L6 4.58579L10.2929 0.292893C10.6834 -0.0976311 11.3166 -0.0976311 11.7071 0.292893C12.0976 0.683417 12.0976 1.31658 11.7071 1.70711L7.41421 6L11.7071 10.2929C12.0976 10.6834 12.0976 11.3166 11.7071 11.7071C11.3166 12.0976 10.6834 12.0976 10.2929 11.7071L6 7.41421L1.70711 11.7071C1.31658 12.0976 0.683417 12.0976 0.292893 11.7071C-0.0976311 11.3166 -0.0976311 10.6834 0.292893 10.2929L4.58579 6L0.292893 1.70711C-0.0976311 1.31658 -0.0976311 0.683417 0.292893 0.292893Z"
                        fill="white" />
                </svg>
            </button>
        </div>
    </main>



    <script src="~/DTCMS/bundle/bundle.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/Pages/Shared/_Layout.cshtml
@using Services.Services.CMS.Setting
@using SharedModels.Dtos


@inject ISettingService SettingService

@{
    // Retrieve global and specific settings


    var settingResponse = SettingService.GetSetting();
    var Setting = settingResponse.IsSuccess ? settingResponse.Model : new SettingSelectDto();

  
 
    bool hideHeaderFooter = ViewData["HideHeaderFooter"] as bool? ?? false;

}

<!DOCTYPE html>
<html lang="fa-IR">

<head>

    <vc:seo-generator setting="Setting"></vc:seo-generator>

     <link href="~/Template/assets/dflip/css/dflip.min.css" rel="stylesheet" type="text/css">

  <!-- Icons Stylesheet -->
    <link href="~/Template/assets/dflip/css/themify-icons.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="~/Template/dist/css/styles.css" asp-append-version="true">
      <!-- Flipbook StyleSheet -->
   
    <link rel="manifest" href="~/Template/manifest/manifest.json">
    <meta name="theme-color" content="#3986D1">

    @await RenderSectionAsync("Header", required: false)
</head>

<body class="font-heading-teko-bold dir-rtl" dir="rtl">

    @if (!hideHeaderFooter)
    {
        <header class="w-full bg-[#1A1A1A]">
            <div class="relative mx-auto flex w-full max-w-6xl items-center justify-between gap-6 px-6 py-3">
                <div class="flex items-center gap-3">
                    <a href="/" class="flex items-center justify-center">
                        <svg width="51" height="51" viewBox="0 0 51 51" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M31.1126 0.0942064C36.511 0.0723699 43.4771 -0.800287 47.2306 3.22976C50.1163 6.32812 50.5495 8.64279 50.591 12.6001L50.6096 31.707C50.6091 37.2869 51.6154 43.2496 47.3311 47.4398C43.2898 51.3922 37.8514 50.6592 32.7177 50.6425L20.4658 50.6355C10.6825 50.6738 0.24894 51.9818 0.116573 38.2863L0.106869 19.9293C0.110104 14.2259 -0.91675 7.67795 3.32978 3.35217C7.35174 -0.74501 13.2252 0.116582 18.4743 0.11739L31.1126 0.0942064Z"
                                fill="url(#paint0_linear_1_49)" />
                            <path
                                d="M26.5051 22.9702C30.5925 23.0463 32.2292 23.2681 35.8015 25.2978C38.0455 27.038 39.5196 28.8812 39.8757 31.8343C40.1607 34.1395 39.5717 36.4674 38.2253 38.3599C34.9191 42.8531 29.3155 42.956 24.2562 42.8528C24.5249 42.0405 24.4648 41.6105 23.841 41.1131L23.049 41.2272C24.4756 40.1251 25.128 39.452 26.3541 38.1445C29.6832 38.0283 33.6699 36.373 32.8107 32.1267C32.4004 30.0992 30.5359 29.0864 28.8486 28.1212C27.4621 28.2436 23.6712 28.1261 22.1138 28.1191C23.376 26.5175 25.1515 24.556 26.5051 22.9702Z"
                                fill="url(#paint1_linear_1_49)" />
                            <path
                                d="M26.5051 22.9702C30.5925 23.0463 32.2292 23.2681 35.8015 25.2978C38.0455 27.038 39.5196 28.8812 39.8757 31.8343C40.1607 34.1395 39.5717 36.4674 38.2253 38.3599C38.2092 37.3761 38.4151 36.3754 38.4256 35.4041C38.4674 31.5293 35.0229 28.9666 31.5132 28.2881C30.6039 28.1121 29.7937 28.1067 28.8486 28.1212C27.4621 28.2436 23.6712 28.1261 22.1138 28.1191C23.376 26.5175 25.1515 24.556 26.5051 22.9702Z"
                                fill="#FEFEFE" />
                            <path
                                d="M21.4379 11.3352C21.4503 11.6821 20.7612 12.4717 20.5248 12.8869C19.7594 14.2311 18.8677 16.0686 18.4824 17.5526C17.4467 21.542 18.7081 25.7359 17.8446 29.5935C16.8746 33.9246 13.1764 36.8464 9.5591 39.0514L9.38683 39.0155C9.11293 38.238 9.15661 26.8518 9.2976 25.4761C9.42511 24.185 9.72597 22.9171 10.1918 21.7067C12.1706 16.6584 16.6263 13.4452 21.4379 11.3352Z"
                                fill="#FEFEFE" />
                            <path
                                d="M20.6669 26.1212C20.5267 24.8776 20.4175 23.631 20.3393 22.382C19.709 10.4323 28.0781 8.21658 38.1094 7.73456C38.709 7.76664 39.139 7.71677 39.601 8.06939C39.7191 8.61125 39.7199 8.39181 39.5123 8.94069C39.0842 9.21378 38.9446 9.22159 38.4426 9.34964C37.9876 9.80767 33.1846 14.5856 33.1091 14.7411L20.6669 26.1212Z"
                                fill="#FEFEFE" />
                            <path
                                d="M38.1094 7.73456C38.9693 7.66716 39.0472 7.51888 39.6924 7.8599C40.4992 10.8402 39.9242 17.9565 38.5949 20.8866C38.0819 22.4691 36.9968 24.1357 35.8014 25.2978C32.2291 23.2681 30.5925 23.0463 26.505 22.9702C27.5928 21.6601 29.3432 19.4268 30.5278 18.328C30.9987 17.4273 33.015 15.6378 33.1091 14.7411C33.1846 14.5856 37.9875 9.80767 38.4426 9.34964C38.9445 9.22159 39.0842 9.21378 39.5123 8.94069C39.7199 8.39181 39.7191 8.61125 39.601 8.06938C39.1389 7.71676 38.7089 7.76664 38.1094 7.73456Z"
                                fill="#B2E8C7" />
                            <path
                                d="M26.505 22.9703C27.5928 21.6601 29.3432 19.4268 30.5278 18.328C30.2913 19.178 30.1188 19.3217 29.5004 19.9716C31.0837 21.088 34.9164 22.9107 36.7851 23.5154C37.2003 22.9198 38.2045 21.2568 38.5949 20.8866C38.0819 22.4691 36.9968 24.1357 35.8014 25.2979C32.2291 23.2681 30.5925 23.0463 26.505 22.9703Z"
                                fill="#90D8B0" />
                            <path
                                d="M20.909 32.6778C22.6667 31.7585 25.3054 30.6632 27.1806 29.8264C27.2904 32.1122 27.3807 34.3722 27.6098 36.6504L25.6928 35.4518C25.0593 36.4838 24.563 37.0634 23.7944 37.9841C24.6422 38.1954 25.4814 38.1491 26.3541 38.1445C25.128 39.452 24.4756 40.1251 23.049 41.2272L23.841 41.1131C24.4648 41.6105 24.5249 42.0405 24.2562 42.8528C22.8109 42.8905 21.4153 42.8509 19.9708 42.8159L14.4009 42.7997L9.95056 42.8167C15.8302 41.0568 19.2227 38.9575 22.6465 33.7459C22.1321 33.3979 21.4511 33.0086 20.909 32.6778Z"
                                fill="#FEFEFE" />
                            <path
                                d="M23.7944 37.984C24.6422 38.1954 25.4814 38.149 26.3541 38.1445C25.128 39.4519 24.4756 40.1251 23.0489 41.2272L23.841 41.1131C24.4648 41.6105 24.5249 42.0405 24.2562 42.8528C22.8109 42.8905 21.4152 42.8509 19.9708 42.8158L14.4009 42.7997C18.5779 42.2513 20.72 40.6481 23.7944 37.984Z"
                                fill="#90D8B0" />
                            <path
                                d="M23.049 41.2272L23.841 41.1131C24.4648 41.6105 24.5249 42.0405 24.2562 42.8528C22.8109 42.8905 21.4153 42.8509 19.9708 42.8158C20.5849 42.443 22.3071 41.6213 23.049 41.2272Z"
                                fill="#B2E8C7" />
                            <defs>
                                <linearGradient id="paint0_linear_1_49" x1="25.2749" y1="50.2359" x2="25.2942" y2="0.36432"
                                    gradientUnits="userSpaceOnUse">
                                    <stop stop-color="#18A96B" />
                                    <stop offset="1" stop-color="#42E480" />
                                </linearGradient>
                                <linearGradient id="paint1_linear_1_49" x1="36.5697" y1="31.4183" x2="23.6163" y2="41.3584"
                                    gradientUnits="userSpaceOnUse">
                                    <stop stop-color="#7DD0A4" />
                                    <stop offset="1" stop-color="#D1F2DE" />
                                </linearGradient>
                            </defs>
                        </svg>


                    </a>

                </div>



                <div class="flex items-center justify-end gap-3">





                    <button class="rounded-md bg-[#28C576] px-5 py-2 text-sm font-semibold text-white transition">
                        درباره ما
                    </button>
                </div>
            </div>
        </header>
    }

    <div>
        @RenderBody()
    </div>

    @if (!hideHeaderFooter)
    {
        <footer class="w-full px-6 py-6  bg-[#1A1A1A]">
            <div
                class="mx-auto flex w-full max-w-6xl flex-col items-center justify-between gap-6 text-white/50 sm:flex-row">
                <div class="flex items-center gap-4">
                    <a class="flex h-10 w-10 items-center justify-center rounded-full border border-white/10 transition hover:border-white/30 hover:text-white"
                        href="#" aria-label="Instagram">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="h-5 w-5">
                            <path
                                d="M7 2a5 5 0 0 0-5 5v10a5 5 0 0 0 5 5h10a5 5 0 0 0 5-5V7a5 5 0 0 0-5-5H7zm0 2h10a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3V7a3 3 0 0 1 3-3zm10 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-5 2a5 5 0 1 0 0 10 5 5 0 0 0 0-10zm0 2a3 3 0 1 1 0 6 3 3 0 0 1 0-6z" />
                        </svg>
                    </a>
                    <a class="flex h-10 w-10 items-center justify-center rounded-full border border-white/10 transition hover:border-white/30 hover:text-white"
                        href="#" aria-label="YouTube">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="h-5 w-5">
                            <path
                                d="M21.8 8.2a2.7 2.7 0 0 0-1.9-1.9C18 6 12 6 12 6s-6 0-7.9.3A2.7 2.7 0 0 0 2.2 8.2 28 28 0 0 0 2 12a28 28 0 0 0 .2 3.8 2.7 2.7 0 0 0 1.9 1.9C6 18 12 18 12 18s6 0 7.9-.3a2.7 2.7 0 0 0 1.9-1.9 28 28 0 0 0 .2-3.8 28 28 0 0 0-.2-3.8zM10 14.7V9.3l4.7 2.7L10 14.7z" />
                        </svg>
                    </a>
                </div>
                <p class="text-sm">
                    ساخته شده با GreenB 🌿
                </p>
            </div>
        </footer>
    }




    <script src="~/Template/assets/dflip/js/libs/jquery.min.js" type="text/javascript"></script>
    <!-- Flipbook main Js file -->
    <script src="~/Template/assets/dflip/js/dflip.min.js" type="text/javascript"></script>
    <script src="~/Template/dist/dist.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>